version: '3.0'
services:
  # web:
  #   build: .
  #   depends_on:
  #     - mongo
  #   command: python -u app.py
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/app
  #   links:
  #     - mongo
  # ngrok:
  #   image: shkoliar/ngrok:latest
  #   ports:
  #     - 5000:5000
  #   links:
  #     - web
  #   environment:
  #     - DOMAIN=web
  #    - PORT=80
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db/mongo
      #- ./data:/data/db
    ports:
      - "27018:27017"

# db:
# image: mongo:3.6.1
