version: '3.0'
services: 
  web:
    build: .
    depends_on: 
      - mongo
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongo

  mongo:
      container_name: mongo
      image: mongo
      restart: always
      volumes:
          - ${WEBAPP_STORAGE_HOME}./si:/data/db/mongo
          #- ./data:/data/db
      ports:
          - "27018:27017"
# db:
  # image: mongo:3.6.1